version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=JvB9IUXIBSCxeu0KiTUKxkVfLG
      - POSTGRES_USER=git-course
      - POSTGRES_DB=default
    healthcheck:
      test: pg_isready -U postgres
  app:
    container_name: app
    image: "app"
    build:
      dockerfile: ./Dockerfile
      context: .
    command: [ "tail", "-f",  "/dev/null" ]
    depends_on:
      db:
        condition: service_healthy

